### ISSUE TITLE
Kotiutuminen typotettu

### ISSUE THREAD

**Issue by meklu** [Tomin1/tj-for-sailfish#6]
Tässä aiheen ajankohtaistuttua tuli huomattua, että pääsivun kotiutumispäivästä puuttuu ensimmäinen u-kirjain.

**Comment by Tomin1** [comment]
Kiitos, vaikkakin sain tästä palautetta jo Jollan tyypeiltä. Korjattu versio on jo täällä Githubissa ja nähtävästi hyväksytty eilen Harbouriin. 93057d8b2f76c29fc333957f4d256e88fcfa3532
